server:
  port: 8005
  
spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pay
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance: 
           # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
      #目的是为了省略resultType里的代码量
  type-aliases-package: com.llf.po,com.llf.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
      
logging:
  level:
    root: INFO
    
sess:
  time-out: 300
